---
- name: Install and Configure MySQL Server
  hosts: mysql_instance  # Change this to your MySQL host or group
  become: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache validity in seconds

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Enable MySQL service
      systemd:
        name: mysql
        enabled: yes

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started

    - name: Create 'nat_user' user for specific IP range
      mysql_user:
        name: nat_user
        password: 'password'
        host: '10.0.2.%'
        priv: '*.*:ALL'
        state: present

    - name: Flush MySQL privileges
      mysql_db:
        name: "*"
        state: import
        login_user: root
        login_password: 'root'  # Replace with the root password, or use a vault

    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted
