---
- name: Install and Configure MySQL Server
  hosts: mysql_instance
  become: yes

  vars:
    mysql_root_password: "your_secure_password"  # Replace with actual root password
    nat_user_password: "password"  # Replace with desired 'nat_user' password

  tasks:
    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL for MySQL interaction
      pip:
        name: PyMySQL
        state: present

    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Enable MySQL service
      systemd:
        name: mysql
        enabled: yes

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started

    - name: Set MySQL root password and authentication method
      shell: |
        sudo mysql <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash

    - name: Create 'nat_user' user for specific IP range
      shell: |
        mysql -u root -p'{{ mysql_root_password }}' <<EOF
        CREATE USER 'nat_user'@'10.0.2.%' IDENTIFIED BY '{{ nat_user_password }}';
        GRANT ALL PRIVILEGES ON *.* TO 'nat_user'@'10.0.2.%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash

    - name: Update MySQL configuration to allow connections from all IPs
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^#?bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted
