---
- name: Install and Configure MySQL Server
  hosts: mysql_instance  # Change this to your MySQL host or group
  become: yes

  tasks:
    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL for MySQL interaction
      pip:
        name: PyMySQL
        state: present
      become: yes

    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache validity in seconds

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Enable MySQL service
      systemd:
        name: mysql
        enabled: yes

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started

    - name: Change MySQL root authentication method to use password
      shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_root_password';
        FLUSH PRIVILEGES;
        EOF
      args:
        creates: /var/lib/mysql/mysql.sock  # Only run this task if MySQL is running

    - name: Create 'nat_user' user for specific IP range
      mysql_user:
        name: nat_user
        password: 'password'
        host: '10.0.2.%'
        priv: '*.*:ALL'
        state: present
        login_user: root
        login_password: 'your_root_password'

    - name: Flush MySQL privileges
      mysql_db:
        name: "*"
        state: import
        login_user: root
        login_password: 'your_root_password'

    - name: Update MySQL configuration to allow connections from all IPs
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf  # Path to MySQL config file
        regexp: '^#?bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted
